"""add ranking updated_at

Revision ID: 9dea61656dd0
Revises: fca5a48a4290
Create Date: 2026-08-30 16:26:50.439210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dea61656dd0'
down_revision: Union[str, Sequence[str], None] = 'fca5a48a4290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_rankings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_rankings', 'updated_at')
    # ### end Alembic commands ###
